before_script:
- python -m venv .venv
- source .venv/bin/activate
- pip install -r requirements.txt -r requirements-test.txt
cache:
  paths:
  - .cache/pip
  - .venv/
deploy:
  only:
  - main
  script:
  - python deployment_script.py
  stage: deploy
quality-gates:
  only:
  - main
  - develop
  script:
  - python quality_gates_validator.py
  stage: quality
stages:
- test
- quality
- deploy
test:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  script:
  - pytest tests/ --cov=. --cov-report=xml
  - python workflow_quality_check.py
  stage: test
variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
