# SwiftLint Configuration

# Disable rules
disabled_rules:
  - trailing_whitespace
  - todo

# Enable opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Configure rules
line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 100

# Exclude files
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - fastlane
  - .git

# Include files
included:
  - CodingReviewer
  - CodingReviewerTests
  - CodingReviewerUITests

# Custom rules
custom_rules:
  print_statements:
    name: "Print Statements"
    regex: "print\\("
    message: "Print statements should not be used in production code"
    severity: warning
