name: Release Automation

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
      
    - name: Build Release Version
      run: |
        echo "🏗️ Building release version..."
        
        xcodebuild -scheme CodingReviewer \
                   -configuration Release \
                   -destination "platform=macOS" \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO
                   
    - name: Run Full Test Suite
      run: |
        echo "🧪 Running full test suite..."
        
        xcodebuild test \
                   -scheme CodingReviewer \
                   -destination "platform=macOS" \
                   CODE_SIGNING_ALLOWED=NO
                   
    - name: Generate Release Notes
      run: |
        echo "📝 Generating release notes..."
        
        # Get version from tag or input
        VERSION="${{ github.ref_name }}"
        if [[ -z "$VERSION" ]]; then
          VERSION="${{ github.event.inputs.version }}"
        fi
        
        mkdir -p release_artifacts
        
        cat > release_artifacts/RELEASE_NOTES.md << EOF
        # CodingReviewer ${VERSION}
        
        Released on $(date -u +%Y-%m-%d)
        
        ## What's New
        
        - Enhanced AI-powered code analysis
        - Improved security scanning capabilities
        - Advanced refactoring suggestions
        - Better performance monitoring
        
        ## Technical Improvements
        
        - Updated MCP integration
        - Enhanced GitHub automation
        - Improved error handling
        - Better logging and debugging
        
        ## Security Updates
        
        - Enhanced security scanning
        - Improved API key management
        - Better input validation
        - Updated dependencies
        
        ---
        
        **Full Changelog**: https://github.com/${{ github.repository }}/compare/previous...${VERSION}
        EOF
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const releaseNotes = fs.readFileSync('release_artifacts/RELEASE_NOTES.md', 'utf8');
          
          const release = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: context.ref.replace('refs/tags/', ''),
            name: `CodingReviewer ${context.ref.replace('refs/tags/', '')}`,
            body: releaseNotes,
            draft: false,
            prerelease: false
          });
          
          console.log(`Release created: ${release.data.html_url}`);
