name: SwiftFormat Check

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.swift'

jobs:
  swiftformat:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftFormat
      run: brew install swiftformat
    
    - name: Create .swiftformat if missing
      run: |
        if [ ! -f ".swiftformat" ]; then
          echo "Creating default .swiftformat configuration..."
          cat > .swiftformat << 'EOF'
        --swiftversion 6.0
        --exclude .build
        --exclude **/*.generated.swift
        --patternlet inline
        --indent 4
        --maxwidth 120
        --linebreaks lf
        --semicolons never
        --trimwhitespace always
        --insertlines enabled
        --removelines enabled
        EOF
        fi
    
    - name: Check formatting
      run: |
        echo "Checking Swift code formatting..."
        if swiftformat . --config .swiftformat --lint; then
          echo "✅ All Swift files are properly formatted"
        else
          echo "❌ Some files need formatting. Run 'swiftformat . --config .swiftformat' locally to fix."
          echo ""
          echo "Files that need formatting:"
          swiftformat . --config .swiftformat --lint --verbose || true
          exit 1
        fi
